{{ $tdropVersion := "0.5.0" -}}
[".local/bin/tdrop"]
  type = "archive-file"
  url = "https://codeload.github.com/noctuid/tdrop/tar.gz/refs/tags/{{ $tdropVersion }}"
  path = "tdrop-0.5.0/tdrop"

# Iosevka SS08 == Pragmata Pro Style
{{ $iosevkaVersion := "28.1.0" -}}
{{ $iosevkaVariant := "SS08" -}}
[".local/share/fonts/Iosevka SS08"]
  type = "archive"
  url = "https://github.com/be5invis/Iosevka/releases/download/v{{ $iosevkaVersion }}/PkgTTF-Iosevka{{ $iosevkaVariant }}-{{ $iosevkaVersion }}.zip"
[".local/share/fonts/Iosevka Fixed SS08"]
  type = "archive"
  url = "https://github.com/be5invis/Iosevka/releases/download/v{{ $iosevkaVersion }}/PkgTTF-IosevkaFixed{{ $iosevkaVariant }}-{{ $iosevkaVersion }}.zip"

{{ $zshVersion := "db085e4661f6aafd24e5acb5b2e17e4dd5dddf3e" -}}
[".zsh/plugins/zsh-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/{{ $zshVersion }}.tar.gz"
  exact = true
  stripComponents = 1
  include = ["*/*.zsh", "*/.version", "*/.revision-hash", "*/highlighters/**"]

{{ $zshCompsVersion := "507f1f8715edd9f1f403c140fa332644d81ebab5" -}}
[".zsh/completitions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-completions/archive/{{ $zshCompsVersion }}.tar.gz"
  exact = true
  stripComponents = 2
  include = ["*/src/_golang", "*/src/_mkcert", "*/src/_node", "*/src/_openssl"]

{{ $obsidianVersion := "1.6.5" -}}
[".local/bin/Obsidian.AppImage"]
  type = "file"
  url = "https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ $obsidianVersion }}/Obsidian-{{ $obsidianVersion }}.AppImage"
  executable = true

[".local/share/icons/hicolor/scalable/apps/obsidian.svg"]
  type = "file"
  url = "https://obsidian.md/images/obsidian-logo-gradient.svg"
  checksum.sha256 = "119b01b96c99f736098742c329f440313b6763bd2aea22cafe08179699431280"
